_target_ : policy.IPA_full.IPA_full
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: concaveTS
bandit_alg_paras : null #for KL_UCB
name : IPA-full

is_reward_known : False
is_cost_known : False
min_sample_required : 0
# prior : ['beta',['linear',1,2],['fixed',1]]
stopping_criteria : null
max_resampling_inc : 1E4
max_resampling_concave : 5E3