_target_ : policy.gEU.gEU
type_arm : participation-based
num_cost_learning : 20
cost_alg : uniformly-space #null
est_reward: increasing-TS
name : gEU
num_optimiser : 16
is_reward_known : True
model_training_appr : T
is_model_known : False #True
prior : null #['beta',['fixed',3],['fixed',1]] #['beta',['linear',1,2],['fixed',1]]s
stopping_criteria : null
likelihood_model : cdf-exp
#For pymc packages
pymc_draws : 500
pymc_tune : 100
pymc_target_accept : 0.9
pymc_cores : 1
pymc_chains : 4