_target_ : policy.linIPA.linIPA
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: UCB-lattimore
name : linIPA
is_cost_known : False
stopping_criteria : null