_target_ : policy.Sigmoid_greedy.Sigmoid_greedy
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
name : Sigmoid-greedy
is_cost_known : False
include_arm0 : True
stopping_criteria : null