_target_ : policy.TS_Gibbs_concave.TS_Gibbs_Concave
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch

bandit_alg: TS-Gibbs-concave
name : IPA-full

is_reward_known : False
is_cost_known : False #True
num_sweeps : 20
sweep_scan : "linear"
eps : 1e-12
min_sample_required : 0 #1
stopping_criteria : null
include_arm0 : True
init_sweep_appr : T