_target_ : policy.TS_MLS.TS_Monotone_LeastSquare
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
name : TS-MLS
is_cost_known : True
need_weighted_LS : True
min_sample_required : 3