_target_ : policy.TS_MLS.TS_Monotone_LeastSquare
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: TS-MLS
name : IPA-full
is_reward_known : False
is_cost_known : False #True
need_weighted_LS : False #True
min_sample_required : 1 #3
stopping_criteria : null
include_arm0 : True