_target_ : policy.TS_MCLS.TS_Monotone_Concave_LeastSquare
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
name : TS-MCLS
is_cost_known : True
need_weighted_LS : True
min_sample_required : 1