_target_ : policy.TS_Gibbs_monotone_EU.TS_Gibbs_Monotone_EU
type_arm : participation-based
num_cost_learning : 0
cost_alg : null #D-optimal #uniformly-space #null
est_reward: TS-Gibb-monotone 
name : TS-EU
num_optimiser : 16
is_reward_known : False
model_training_appr : T
is_model_known : False #True
prior : null #['beta',['fixed',3],['fixed',1]] #['beta',['linear',1,2],['fixed',1]]s

num_sweeps : 20
random_scan : True
eps : 1e-12
init_sweep_appr : T