_target_ : policy.IPA_full.IPA_full
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: UTS #UCB-lattimore
bandit_alg_paras : null #for KL_UCB
name : IPA-full

is_reward_known : False
is_cost_known : False
min_sample_required : 1
# prior : ['beta',['linear',1,2],['fixed',1]]
stopping_criteria : null
max_resampling_inc : null #1E7
max_resampling_concave : null #1E6