_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.41,0.42,0.43,0.44,0.45,0.46,0.47,0.48,0.49,0.50] 
success_value : 1
name: max050_gap001_end_10arm
type : pre-defined