_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.815,0.82,0.83,0.84,0.85,0.90,0.85,0.84,0.83,0.82,0.815]  
success_value : 1
name: max090_spike005_mid_11arm
