_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.5,0.625,0.725,0.775,0.825,0.875,0.885,0.895,0.90,0.895] 
success_value : 1
name: max090_cave0005_rear_10arm
