_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.81,0.82,0.83,0.84,0.85,0.86,0.87,0.88,0.89,0.90] 
success_value : 1
name: max090_gap001_end_10arm
type : pre-defined