_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [
    0.65, 0.66, 0.67, 0.68, 0.69, 
    0.7, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 
    0.8, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 
    0.9, # Middle Peak
    0.89, 0.88, 0.87, 0.86, 0.85, 0.84, 0.83, 0.82, 0.81, 0.8, 
    0.79, 0.78, 0.77, 0.76, 0.75, 0.74, 0.73, 0.72, 0.71, 0.7, 
    0.69, 0.68, 0.67, 0.66, 0.65, 
]
success_value : 1
name: max090_gap001_mid_51arm
