_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.4,0.8,0.9,0.91,0.92,0.93,0.94,0.95,0.96,0.97] #[0.5,0.7,0.85,0.9,0.92,0.94,0.95,0.96,0.97,0.98]
success_value : 1
