_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.65,0.70,0.75,0.80,0.85,0.90,0.85,0.80,0.75,0.70,0.65] 
success_value : 1
name: max090_gap005_mid_11arm
type : pre-defined