_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.875,0.880,0.885,0.890,0.895,0.90,0.895,0.890,0.885,0.880,0.875] 
success_value : 1
name: max090_gap0005_mid_11arm
type : pre-defined