_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.8735,0.8740,0.8745,0.875,0.876,0.880,0.885,0.89,0.90,0.89] 
success_value : 1
name: max090_spike001_rear_10arm
