_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.40,0.50,0.60,0.70,0.80,0.90,0.80,0.70,0.60,0.50,0.40] 
success_value : 1
name: max090_gap010_mid_11arm
type : pre-defined