_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.2,0.4,0.4,0.4,0.4,0.62,0.65,0.68,0.71,0.73] 
success_value : 1
type : pre-defined
#use with MABA_10lc3 or MABA_10lc4
