_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [0.45,0.46,0.47,0.48,0.49,0.50,0.49,0.48,0.47,0.46,0.45] 
success_value : 1
name: max050_gap001_mid_11arm
type : pre-defined