_target_ : Reward_generator.Participation_based_Reward
type_dist : Bernoulli
mean_prob : [
    0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 
    0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1
    ]
success_value : 1
name: UMAB17
type : pre-defined
