defaults:
  - _self_
  - setting : MABA_10lc2
  - policy : TS #IPA_full #longEU
  - reward_generator : bernoulli_inc_rand #bernoulli_bounded_log #poly #bounded_log #mono_logistic
num_sim : 10000
max_round : 10000
wandb_mode : online