defaults:
  - _self_
  - setting : MABA_10hlc2
  - policy : IPA_full #longEU
  - reward_generator : bernoulli_mono_logistic #bounded_log #mono_logistic
num_sim : 100
max_round : 1000
wandb_mode : online