defaults:
  - _self_
  - setting : MABA_5lc
  - policy : TS #IPA_full #longEU
  - reward_generator : bernoulli_cave_rand #bernoulli_bounded_log #poly #bounded_log #mono_logistic
num_sim : 100
max_round : 10000
wandb_mode : online