defaults:
  - _self_
  - setting : MABA_10IncUni #left
  - policy : TS #IPA_full #longEU
  - reward_generator : bernoulli_inc_rand #bernoulli_bounded_log #poly #bounded_log #mono_logistic
num_sim : 1
max_round : 10
wandb_mode : offline