_target_ : MABA_model.MABA_model
num_agent : 10 #provide practically uniform dist over increasing func
agent_cost : [0.0909, 0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909,0.0909]
type : null 
init_seed_id : 0